/**
 * Study protocol contract.
 * Owned by: Protocol Architect (Agent 00)
 * Read by: all agents.
 *
 * DO NOT modify without coordinating all dependent agents.
 */

export interface StudyProtocol {
  study_id: string;
  study_uuid: string; // UUID, generated at creation
  version: number; // increment on any change

  schedule: ScheduleConfig;
  assessments: AssessmentConfig[];
  context_collection: ContextCollectionConfig;
}

export interface ScheduleConfig {
  /** Local-time windows during which prompts may fire. */
  windows: Array<{ start: string; end: string }>; // "HH:MM" format

  /** Number of prompts per day. Must fit within windows with min_gap_minutes spacing. */
  prompts_per_day: number;

  /** If true, pick a random time within each sub-window. If false, space evenly. */
  randomize_within_window: boolean;

  /**
   * Minutes after prompt delivery before it is marked expired.
   * Also controls how long the app shows the assessment after notification tap.
   */
  expiry_minutes: number;

  /** Total study duration in days. */
  days_total: number;

  /** Minimum gap between consecutive prompts in minutes. Default 30. */
  min_gap_minutes: number;
}

export interface AssessmentConfig {
  /** Must match activity_id in the m2c2kit assessment package. */
  activity_id: string;

  /** Version of the assessment package used at protocol creation time. */
  activity_version: string;

  /**
   * Parameter overrides — merged with assessment defaults.
   * Keys must match parameter names in the assessment's schemas.json.
   */
  parameters: Record<string, unknown>;

  /**
   * How to select assessments when multiple configs are present.
   * "all" = run every assessment each prompt (default)
   * "random_one" = pick one at random per prompt
   * "round_robin" = cycle through assessments across prompts
   */
  selection_strategy?: "all" | "random_one" | "round_robin";

  /** Run order when selection_strategy is "all". Lower numbers run first. */
  order?: number;
}

export interface ContextCollectionConfig {
  /** Collect GPS location when a prompt fires. */
  gps_on_prompt: boolean;

  /**
   * If set, also collect GPS every N minutes in the background (passive tracking).
   * Null means prompt-only.
   */
  gps_interval_minutes: number | null;

  /** Collect battery level and charging state. */
  collect_battery: boolean;

  /** Collect network connection type (wifi / cellular / none). */
  collect_network_type: boolean;
}

/** A single computed prompt slot derived from StudyProtocol. */
export interface ScheduledPrompt {
  prompt_id: string; // UUID, generated by scheduler
  study_id: string;
  participant_id: string;
  scheduled_for: string; // ISO 8601 (local time, UTC offset included)
  day_index: number; // 0-based day within study
  window_index: number; // which window within the day
  slot_index: number; // which slot within the window
}
